// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlZCpS4i58n9sR0MxbK2nT3EhN63jUOMg',
    appId: '1:198014026663:web:ce1a73c095b9e6fd4a6c82',
    messagingSenderId: '198014026663',
    projectId: 'test-f7173',
    authDomain: 'test-f7173.firebaseapp.com',
    databaseURL: 'https://test-f7173-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-f7173.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmjTKFR6fLF11APWAeBHuhRbltRBTwAKE',
    appId: '1:198014026663:android:4ccf5cc9983261b24a6c82',
    messagingSenderId: '198014026663',
    projectId: 'test-f7173',
    databaseURL: 'https://test-f7173-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-f7173.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC46alSzf9bQApW6VikSR5Ad1f5NgioCb0',
    appId: '1:198014026663:ios:e766eab11703d4694a6c82',
    messagingSenderId: '198014026663',
    projectId: 'test-f7173',
    databaseURL: 'https://test-f7173-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-f7173.appspot.com',
    iosBundleId: 'com.example.firebaseMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC46alSzf9bQApW6VikSR5Ad1f5NgioCb0',
    appId: '1:198014026663:ios:a4b1dab7546798304a6c82',
    messagingSenderId: '198014026663',
    projectId: 'test-f7173',
    databaseURL: 'https://test-f7173-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-f7173.appspot.com',
    iosBundleId: 'com.example.firebaseMaster.RunnerTests',
  );
}
